"""add company auth fields

Revision ID: 7852c245f7fd
Revises: f420930c27fb
Create Date: 2026-09-08 13:06:37.751374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7852c245f7fd'
down_revision: Union[str, Sequence[str], None] = 'f420930c27fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'hashed_password')
    # ### end Alembic commands ###
