"""Initial migration

Revision ID: cbcebad8122b
Revises: 
Create Date: 2026-09-08 12:39:46.354241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcebad8122b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('vehicles_requested', sa.Integer(), nullable=False),
    sa.Column('vehicle_capacity', sa.Float(), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('baseline_distance_km', sa.Float(), nullable=True),
    sa.Column('baseline_cost', sa.Float(), nullable=True),
    sa.Column('cost_reduction_pct', sa.Float(), nullable=True),
    sa.Column('vehicles_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_company_id'), 'optimization_runs', ['company_id'], unique=False)
    op.create_table('stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('demand', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stops_company_id'), 'stops', ['company_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('stop_ids', sa.JSON(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_company_id'), 'routes', ['company_id'], unique=False)
    op.create_index(op.f('ix_routes_run_id'), 'routes', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_run_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_company_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_stops_company_id'), table_name='stops')
    op.drop_table('stops')
    op.drop_index(op.f('ix_optimization_runs_company_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_table('companies')
    # ### end Alembic commands ###
